---
- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd config
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
